export class ProductPhonePath {

}

export class FeatureMainPath{
  static readonly LOADING = "main/SplashPage"
  static readonly MAIN = "main/MainPage"
}

export class FeatureUserPath {
  static readonly COLLECT = "user/CollectListPage"
}

export class FeatureCoursePath {
}

export class FeatureSquarePath {
}



export class FeatureHomePath {
  static readonly HOME = "Home/HomePage"
  static readonly LOGIN = "Home/LoginPage"
}